### ISSUE TITLE
IDR SILHOUETTE LOSS PARAMETERS

### ISSUE THREAD

**Issue by BanKeTang** [superxjm/HybridTransparentRecon#1]
Hello, I saw in your paper Figure 6 that you provided an initialization model for IDR reconstruction using only mask loss. Could you please provide the model parameters (.conf file) to achieve this result? Thank you.

**Comment by superxjm** [comment]
Hi, I use the default .conf file in IDR, with the belowing modifications:
1. Increase the number of rays sampled from an image to 20800; 
2. Set batch sizes equals three, which means each batch contained rays sampled from three images.
