### ISSUE TITLE
dataset link

### ISSUE THREAD

**Issue by HollyDQWang** [superxjm/HybridTransparentRecon#2]
the download link for dataset doesn't work.

**Comment by superxjm** [comment]
Sorry, I have updated the download link. Please check.

**Comment by HollyDQWang** [comment]
thanks!

**Comment by HollyDQWang** [comment]
In your released data, the recovered mesh from VSA doesn't look better than using mask loss only. is this a wrong upload?

**Comment by superxjm** [comment]
Hi, the VSA mesh has the same shape compared with the reconstructed mesh using mask loss.

Because VSA only segments the mesh. It is the input of our second stage refinement.

**Comment by HollyDQWang** [comment]
Thank you for your quick reply! In this case may I ask how do we obtain the final output mesh as in your paper?

**Comment by superxjm** [comment]
Please download the final mesh using this link: https://pan.baidu.com/s/1gzxqrjFjvamzcVFSIpLYxw 
Extraction code：TRAN
